services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    environment:
      - ENVIRON=${ENVIRON}
      - TIMEZONE=${TIMEZONE}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python main.py
    container_name: myside_api
    networks:
      - myside_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

networks:
  myside_network:
    driver: bridge
    name: myside_network
